# All questions on classicmodels database

-- 1.List the total number of products in each product line.
use classicmodels;
select * from products;
select productLine,count(*) from products group by  productLine;
-- 2.Retrieve the total quantity of products ordered per order.
select * from orderdetails;
select orderNumber,sum(quantityOrdered) from orderdetails group by orderNumber;
-- 3. Find the number of orders for each order status.
select * from orders;
select status,count(*) from orders group by status;
--  4.Calculate the total revenue generated by each product.
select * from orderdetails;
select productCode,sum(quantityOrdered*priceEach) as total_revenue from orderdetails group by productCode;
-- 5.Find the average credit limit for each country.
select * from customers;
select country,avg(creditLimit) from customers group by country;
-- 6. Find the top 3 customers with the highest total payments.
select * from payments;
select customerNumber,sum(amount)from payments group by customerNumber order by sum(customerNumber) desc limit 3;
-- 7. Find the total number of products supplied by each vendor.
select * from products;
select productVendor,count(productLine) as products_supplied  from products group by productVendor;
-- 8. Retrieve all customers sorted by country and then by customer name in ascending order.
select * from customers;
select customerNumber,customerName,country from customers order by  country,customerName;### by default ordewr by in ascending order
-- 9. List all orders sorted by order date in descending order.
select * from orders;
select orderNumber,orderDate from orders order by orderDate desc;
-- 10. Show the top 5 highest-paying customers.
select * from payments;
select customerNumber,sum(amount) from payments group by customerNumber order by customerNumber desc limit 5;
-- 11. Retrieve product details sorted by quantity in stock in descending order.
select * from products;
select productCode,productName,quantityInStock,productLine from products order by quantityInStock desc;
-- 12. Get the employees sorted by their job title in alphabetical order(a to z)
select * from employees;
select employeeNumber,firstName,lastName,jobTitle from employees order by jobTitle ;
-- 13. Get the month-wise total sales for the year 2004.
select * from payments;
select month(paymentDate),sum(amount)from payments where year(paymentDate)=2004 group by month(paymentDate) order by month(paymentDate);
-- 14. Display the orders placed on weekends (Saturday & Sunday).
select * from orders;
select orderNumber,orderDate,status from orders where dayofweek(orderDate) in(1,7);
